# Generated by Django 4.1.1 on 2022-10-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('number', models.IntegerField()),
                ('text', models.TextField(max_length=240)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
